name: Manual Test Action
on:
  workflow_dispatch:

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read changelog
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: CHANGELOG.md
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_TEST_URL }}
          username: Project MMO Updates
          content: ${{ steps.changelog.outputs.content }}
          avatar-url: https://github.com/Caltinor/Project-MMO-2.0/blob/main/src/main/resources/star.png